---
version: '3'

services:
  bot:
    image: python:alpine
    restart: always
    environment:
      - api_key=
      - db_conn=  # postgresql://wowuser:wowpass@localhost:5432/wowdb
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=wowdb
      - POSTGRES_USER=wowuser
      - POSTGRES_PASSWORD=wowpass
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
