[tool.poetry]
name = 'dongdong'
version = '0.1.0'
description = 'dangi dongi'

license = 'MIT'

authors = [
	'Mahan Talebi <mahantalebi100@gmail.com>'
]

readme = 'README.md'


[tool.poetry.dependencies]
python = '^3.9'
toml = '^0.9'
peewee = "^3.15.4"
botogram = "^0.5"
pytz = "^2022.7.1"
